project:
  type: website
  output-dir: docs

website:
  title: "Firdauz Quatro Exercise"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Project
      - href : Movies.qmd
        text: Movies
      - href: Contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual

